WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)
SELECT H.HOUR, COALESCE(COUNT(AO.DATETIME), 0) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS AO ON DATE_FORMAT(AO.DATETIME, "%H") = LPAD(H.HOUR, 2, '0')
GROUP BY H.HOUR
ORDER BY H.HOUR ASC;