SELECT DATE_FORMAT(OS.SALES_DATE , "%Y") AS YEAR ,
        DATE_FORMAT(OS.SALES_DATE , "%m") AS MONTH ,
        UI.GENDER , COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE OS
    INNER JOIN USER_INFO UI ON(UI.USER_ID = OS.USER_ID AND UI.GENDER IS NOT NULL)
GROUP BY YEAR , MONTH , UI.GENDER
ORDER BY YEAR ASC , MONTH ASC , UI.GENDER;