SELECT UGB.BOARD_ID , UGB.WRITER_ID , UGB.TITLE , UGB.PRICE ,
        (
        CASE
            WHEN UGB.STATUS = "SALE" THEN "판매중"
            WHEN UGB.STATUS = "RESERVED" THEN "예약중"
            WHEN UGB.STATUS = "DONE" THEN "거래완료"
            ELSE ""
        END
        ) AS STATUS
FROM USED_GOODS_BOARD UGB
WHERE UGB.CREATED_DATE = "2022-10-05"
ORDER BY UGB.BOARD_ID DESC;