SELECT FP.CATEGORY , MAX(FP.PRICE) AS MAX_PRICE , 
        (
            SELECT PRODUCT_NAME 
            FROM FOOD_PRODUCT
            WHERE CATEGORY = FP.CATEGORY
                AND PRICE = MAX(FP.PRICE)
        ) AS PRODUCT_NAME
FROM FOOD_PRODUCT FP
WHERE FP.CATEGORY IN('과자', '국', '김치', '식용유')
GROUP BY FP.CATEGORY
ORDER BY MAX(FP.PRICE) DESC;