SELECT OS.*
FROM (
    SELECT DATE_FORMAT(OS.SALES_DATE , "%Y-%m-%d") AS SALES_DATE ,
            OS.PRODUCT_ID , OS.USER_ID , OS.SALES_AMOUNT
    FROM ONLINE_SALE OS
    UNION
    SELECT DATE_FORMAT(OS.SALES_DATE , "%Y-%m-%d") AS SALES_DATE ,
            OS.PRODUCT_ID , NULL AS USER_ID , OS.SALES_AMOUNT
    FROM OFFLINE_SALE OS
    ) OS
WHERE DATE_FORMAT(OS.SALES_DATE , "%Y-%m") = "2022-03"
ORDER BY OS.SALES_DATE ASC , OS.PRODUCT_ID ASC , OS.USER_ID ASC;