SELECT CR.HISTORY_ID , CR.CAR_ID ,
        DATE_FORMAT(CR.START_DATE , "%Y-%m-%d") AS START_DATE , 
        DATE_FORMAT(CR.END_DATE , "%Y-%m-%d") AS END_DATE ,
        IF(DATEDIFF(CR.END_DATE , CR.START_DATE) + 1 >= 30 , "장기 대여" , "단기 대여") AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
WHERE DATE_FORMAT(CR.START_DATE , "%Y-%m") = "2022-09"
ORDER BY CR.HISTORY_ID DESC;