SELECT DISTINCT OS.USER_ID , OS.PRODUCT_ID
FROM ONLINE_SALE OS
WHERE (
        SELECT COUNT(*)
        FROM ONLINE_SALE
        WHERE USER_ID = OS.USER_ID
            AND PRODUCT_ID = OS.PRODUCT_ID
    ) > 1
ORDER BY OS.USER_ID ASC , OS.PRODUCT_ID DESC;