SELECT T.HISTORY_ID ,
        (
            CASE 
                WHEN T.DAY BETWEEN 7 AND 29 THEN T.DAY * (T.DAILY_FEE - (T.DAILY_FEE / 100 * T.DISCOUNT_RATE1))
                WHEN T.DAY BETWEEN 30 AND 89 THEN T.DAY * (T.DAILY_FEE - (T.DAILY_FEE / 100 * T.DISCOUNT_RATE2))
                WHEN T.DAY >= 90 THEN T.DAY * (T.DAILY_FEE - (T.DAILY_FEE / 100 * T.DISCOUNT_RATE3))
                ELSE T.DAY * T.DAILY_FEE
            END
        ) AS FEE
FROM (
    SELECT CRCRH.HISTORY_ID , 
            CRCC.DAILY_FEE , 
            DATEDIFF(CRCRH.END_DATE , CRCRH.START_DATE) + 1 AS DAY ,
            REPLACE(CRCDP1.DISCOUNT_RATE , "%" , "") AS DISCOUNT_RATE1 ,
            REPLACE(CRCDP2.DISCOUNT_RATE , "%" , "") AS DISCOUNT_RATE2 ,
            REPLACE(CRCDP3.DISCOUNT_RATE , "%" , "") AS DISCOUNT_RATE3
    FROM CAR_RENTAL_COMPANY_CAR CRCC
        INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON(CRCRH.CAR_ID = CRCC.CAR_ID)
        INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP1 ON(CRCDP1.CAR_TYPE = CRCC.CAR_TYPE AND CRCDP1.DURATION_TYPE = "7일 이상")
        INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP2 ON(CRCDP2.CAR_TYPE = CRCC.CAR_TYPE AND CRCDP2.DURATION_TYPE = "30일 이상")
        INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP3 ON(CRCDP3.CAR_TYPE = CRCC.CAR_TYPE AND CRCDP3.DURATION_TYPE = "90일 이상")
    WHERE CRCC.CAR_TYPE = "트럭"
) T
ORDER BY FEE DESC , T.HISTORY_ID DESC;