SELECT DATE_FORMAT(START_DATE , "%m") AS MONTH , CR.CAR_ID , COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
WHERE (
        SELECT COUNT(*)
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE DATE_FORMAT(START_DATE , "%Y-%m") BETWEEN "2022-08" AND "2022-10"
            AND CAR_ID = CR.CAR_ID
    ) >= 5
    AND DATE_FORMAT(START_DATE , "%Y-%m") BETWEEN "2022-08" AND "2022-10"
GROUP BY MONTH , CR.CAR_ID
ORDER BY MONTH ASC , CR.CAR_ID DESC;