SELECT DISTINCT UGU.USER_ID , UGU.NICKNAME , 
        CONCAT(UGU.CITY," ",UGU.STREET_ADDRESS1," ",UGU.STREET_ADDRESS2) AS 전체주소 ,
        CONCAT(SUBSTR(UGU.TLNO, 1, 3), '-', SUBSTR(UGU.TLNO, 4, 4), '-', SUBSTR(UGU.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD UGB
    LEFT JOIN USED_GOODS_USER UGU ON(UGU.USER_ID = UGB.WRITER_ID)
WHERE (
        SELECT COUNT(*)
        FROM USED_GOODS_BOARD
        WHERE WRITER_ID = UGB.WRITER_ID
    ) >= 3
ORDER BY UGU.USER_ID DESC;